Branch portfolio1 submited for approval to merge into the master branch
DarioAlessioR/my-portfolio pull request #2
Opened 2022-04-23 21:18 UTC by DarioAlessioR

This is to request approval to merge branch protfolio1 of project my-portfolio into the master branch.

Thank you in advance for your review.

2022-04-23 22:13 UTC, prolajumokeoni requested changes
Hi @DarioAlessioR, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used



## Required Changes ♻️

- [ ] Kindly add a descriptive pull request title describing changes made in your pull request
- [ ] Please add a short summary pull request message describing changes made in your pull request in more detail

_Check the comments under the review._

 

 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 22:13 UTC, prolajumokeoni commented on PortafolioMobile.html
> +    <section id="works">
- [ ] Kindly add `display: grid` to the main container for the projects, please do this as  it is part of the project requirements 👍🏿 


Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_44](https://user-images.githubusercontent.com/69638013/164947369-965dfc59-8330-4f15-8572-5bf6038c209d.png) |  ![Screenshot_45](https://user-images.githubusercontent.com/69638013/164947402-88ccf692-303d-4f77-aca0-56350ed94314.png)

- For each card: 

- [ ] It would be better to  align the p text content and make them have same width with figma design, please see screenshots above
- [ ] Kindly remove the red border outline and add the right border add color used in the figma design 👍🏿 
- [ ] Please add the same color use for the buttons in the fima design and ensure to add all button interactions, see screenshot below ⬇️ 
 
![Screenshot_46](https://user-images.githubusercontent.com/69638013/164947485-8f59b0c2-db59-49e8-8a36-a068b8012498.png)

2022-04-23 22:13 UTC, prolajumokeoni commented on PortafolioMobile.html
> +            <img src="images/portfolio/Fugados.png" alt="" />
- [ ] Please add alt text to all images this is important so when browsers are unable to render a page properly a text is displayed 👍🏿

2022-04-23 22:13 UTC, prolajumokeoni commented on PortafolioMobile.html
> +            <img src="images/portfolio/most-useful-websites.jpg" alt="" />
- [ ] Please add alt text to all images this is important so when browsers are unable to render a page properly a text is displayed 👍🏿

2022-04-23 22:13 UTC, prolajumokeoni commented on PortafolioMobile.html
> +            <img src="images/portfolio/work1.jpg" alt="" />
- [ ] Please add alt text to all images this is important so when browsers are unable to render a page properly a text is displayed 👍🏿

2022-04-23 22:13 UTC, prolajumokeoni commented on PortafolioMobile.html
> +            <img src="images/portfolio/Website.png" alt="" />
- [ ] Please add alt text to all images this is important so when browsers are unable to render a page properly a text is displayed 👍🏿

2022-04-23 22:13 UTC, prolajumokeoni commented on PortafolioMobile.html
> +        <h2>My recent woks</h2>
- [ ] Kindly align header  text and border to have same spacing like the figma design, check screenshot below ⬇️ 
- [ ]  The header text be on two line 👍🏿 

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_41](https://user-images.githubusercontent.com/69638013/164947263-5e2ce721-b2c7-4818-ab53-191622e31528.png)| ![Screenshot_40](https://user-images.githubusercontent.com/69638013/164947259-24ebc20a-af09-4677-972e-d997fc3b3ecd.png)

2022-04-24 01:55 UTC, DarioAlessioR commented
This is to request approval to merge branch protfolio1 of project my-portfolio into the master branch after correcting errors detected in the first review by reviewer @prolajumokeoni .

Changes that were done:

- Display: grid added.
- Style of the title of works section changed to be shown in 2 lines
- Typo error corrected in word "works" of title
- p text content aligned in the works section
- Alt text added to all images
- Red border outline of languages used in the works section changed to Figma style
- Color of the buttons in the works section changed to the color used in the Figma template
- Color of buttons in the works section was established for any case of the 4 possible interactions according to Figma template.
- Description of comment of pull request increased according to reviewer requirement and best practices.

Thank you in advance for your review @prolajumokeoni .

2022-04-24 02:02 UTC, omar-labana commented
# **Approved ✔️**

Hi @DarioAlessioR,

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-24 02:04 UTC, omar-labana commented
@DarioAlessioR Hello daniel, there seems to be an issue with your linters that was't loaded when making the review, kindly fix it before starting the next milestone

2022-04-24 02:20 UTC, DarioAlessioR commented
Project ready to merge into master branch after approved in second revision by @omar-labana .

The issue regarding linters will be fixed ASAP. Thank you for the information and advice @omar-labana  and @prolajumokeoni .

2022-04-24 02:26 UTC, merged