PR for activity add Contact section to mobile project
DarioAlessioR/my-portfolio pull request #4
Opened 2022-05-03 18:28 UTC by DarioAlessioR

PR to ask for approval to marge branch profolioContact into the master branch.

Branch porfolioContact contains the following changes:
- Add form for name, last name, email, and message.
- Add social media icons.
- Add email at end of the page

Features or functionalities added:
- Name field accepts up to 30 chars.
- Email field accepts only emails.
- The message field accepts up to 500 chars.
- All fields have placeholder text.
- All fields have the correct type.
- A user cannot submit the form if one or more of the fields is empty.
- Collect data by using the [Formspree service](https://formspree.io/html).
- Use Flexbox.

Changes done while pair programming with https://github.com/Marlyn-Mayienga

Thank you in advance for review.

2022-05-03 18:40 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @DarioAlessioR 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
- [ ] Please make sure that every member from your coding partner group has contributed to this project, I can only see your commits, I am requesting some changes Implement the changes with your group in pair programming we will check the commit history.
- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 18:40 UTC, thecodechaser commented on index.html
> +          <input type="text" id="lastname" name="user_last_name" placeholder="Last name" required minlength="1" maxlength="30">
- [ ] Please make sure to use only one input field for the name.

2022-05-03 18:40 UTC, thecodechaser commented on index.html
> +          <input type="text" id="lastname" name="user_last_name" placeholder="Last name" required minlength="1" maxlength="30">
- [ ] Please use correct paddings for the input fields and make sure it matches the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10) design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/166520079-ae18fc04-6ad6-479d-8b7c-1eb858b382d9.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/166520105-8de32eff-1a6c-4162-be8f-9eb2e838a19e.png)

2022-05-03 18:40 UTC, thecodechaser commented on index.html
> +            <button class="superButton" type="submit">Send</button>
- [ ] Please increase padding for the submit button and make sure it matches with the design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/166520291-405f292a-7806-42b7-a4c9-91222cdc3a7e.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/166520335-c4d99c09-156e-4363-a680-9093881f6a94.png)

2022-05-03 18:40 UTC, thecodechaser commented on index.html
> +          <li><a href="#" target="new"><i class="fab fa-twitter social-icon"></i></a></li>
- [ ] Please reduce the gap between social media icons and make sure it matches the design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/166520560-5dd8b9f6-193f-4fc2-8076-8db3239ee898.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/166520601-d2afa08a-b561-4dff-b33a-e9cc837ede2a.png)

2022-05-03 20:49 UTC, DarioAlessioR reviewed
Changes commited by Marlyn approved

2022-05-04 00:21 UTC, DarioAlessioR commented
PR ready after required changes were done. 

Project ready to ask for a new review.

Changes were done with coding partner @Marlyn-Mayienga 

Thank you in advance.

2022-05-04 00:27 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 01:35 UTC, DarioAlessioR commented
Project ready to merge after approval is received from the reviewer.

2022-05-04 01:36 UTC, merged